### ISSUE TITLE
BadResponseException

### ISSUE THREAD

**Issue by throwNPE** [QIWI-API/bill-payments-java-sdk#11]
Появилась ошибка
`Exception in thread "Thread-54" com.qiwi.billpayments.sdk.exception.BadResponseException: ResponseData{body='{"siteId":"*","billId":"*","amount":{"currency":"RUB","value":"1.00"},"status":{"value":"PAID","changedDateTime":"2020-02-14T22:43:45.596+03:00"},"customer":{"email":"email","phone":"phone","account":"*"},"customFields":{"apiClient":"java_sdk","apiClientVersion":"1.4.0","CHECKOUT_REFERER":"https://away.vk.com/"},"comment":"Пополнение баланса","creationDateTime":"2020-02-14T22:43:12.416+03:00","expirationDateTime":"2020-02-15T22:43:13.412+03:00","payUrl":"*"}', httpStatus=200}`

Хотя все раньше работало

**Comment by Senderman** [comment]
Confirmed, the same thing. And as I understood, it's only for PAID bills

**Comment by Senderman** [comment]
Ошибка в классе RequestMapperIntercessor, в private <T> T deserializeResponseBody(Class<T> responseClass, ResponseData response)
Причина ошибки - сервер Qiwi API стал возвращать json у которого в custom fields появилось новое свойство - CHECKOUT_REFERER. И библиотека fasterxml валится от этого. В общем фикс - докинуть свойство CHECKOUT_REFERER в класс CustomFields

**Comment by Mike497** [comment]
Здравствуйте, ошибка появилась вновь при вызове com.qiwi.billpayments.sdk.client.BillPaymentClient#createBill.

**Comment by AmazZ1nG** [comment]
> Здравствуйте, ошибка появилась вновь при вызове com.qiwi.billpayments.sdk.client.BillPaymentClient#createBill.

Тоже самое появилось

**Comment by Senderman** [comment]
@Mike497 @AmazZ1nG приложите стектрейс актуальный: как в шапке :) Может снова что-то в апи добавили/убрали?

**Comment by xxCarLyy** [comment]
@Senderman 

`Exception in thread "main" com.qiwi.billpayments.sdk.exception.BadResponseException: ResponseData{body='{"siteId":"*","billId":"*","amount":{"currency":"RUB","value":"1.00"},"status":{"value":"WAITING","changedDateTime":"2022-05-15T19:38:20.915+03:00"},"customer":{"email":"*","account":"*","phone":"*"},"customFields":{"apiClient":"java_sdk","apiClientVersion":"1.5.0"},"comment":"Hello World","creationDateTime":"2022-05-15T19:38:20.915+03:00","expirationDateTime":"2022-06-29T19:38:20.702+03:00","payUrl":"*","recipientPhoneNumber":"*"}', httpStatus=200}`

**Comment by xxCarLyy** [comment]
@Senderman или держи этот.

`Exception in thread "main" com.qiwi.billpayments.sdk.exception.BadResponseException: ResponseData{body='{"siteId":"*","billId":"*","amount":{"currency":"RUB","value":"1.00"},"status":{"value":"PAID","changedDateTime":"2022-05-15T18:55:37.84+03:00"},"customer":{"email":"*","phone":"*","account":"*"},"customFields":{"apiClient":"java_sdk","apiClientVersion":"1.5.0"},"comment":"Hello World","creationDateTime":"2022-05-15T18:51:38.245+03:00","expirationDateTime":"2022-06-29T18:51:37.942+03:00","payUrl":"*","recipientPhoneNumber":"*"}', httpStatus=200}
`

**Comment by Senderman** [comment]
Опять поменяли ответ от сервера:) добавили поле recipientPhoneNumber
А уже есть #23 , если вольют - то проблема уйдет

**Comment by xxCarLyy** [comment]
Пойду тогда сбилжу тот. спасибо
