### ISSUE TITLE
com.qiwi.billpayments.sdk.exception.BadResponseException

### ISSUE THREAD

**Issue by kaiyofx** [QIWI-API/bill-payments-java-sdk#28]
> [21:30:53 ERROR]: [org.telegram.telegrambots.updatesreceivers.DefaultBotSession] ResponseData{body='{"siteId":"*","billId":"*","amount":{"currency":"RUB","value":"1.00"},"status":{"value":"WAITING","changedDateTime":"2022-07-28T16:30:54.039+03:00"},"customer":{"email":"*","account":"*","phone":"*"},"customFields":{"apiClient":"java_sdk","apiClientVersion":"1.5.0"},"comment":"*","creationDateTime":"2022-07-28T16:30:54.039+03:00","expirationDateTime":"2022-07-28T16:33:53.446+03:00","payUrl":"https://oplata.qiwi.com/form/?invoice_uid=*","recipientPhoneNumber":"*"}', httpStatus=200}
> com.qiwi.billpayments.sdk.exception.BadResponseException: ResponseData{body='{"siteId":"*","billId":"*","amount":{"currency":"RUB","value":"1.00"},"status":{"value":"WAITING","changedDateTime":"2022-07-28T16:30:54.039+03:00"},"customer":{"email":"*","account":"*","phone":"*"},"customFields":{"apiClient":"java_sdk","apiClientVersion":"1.5.0"},"comment":"*","creationDateTime":"2022-07-28T16:30:54.039+03:00","expirationDateTime":"2022-07-28T16:33:53.446+03:00","payUrl":"https://oplata.qiwi.com/form/?invoice_uid=*","recipientPhoneNumber":"*"}', httpStatus=200}
>         at com.qiwi.billpayments.sdk.client.RequestMappingIntercessor.mapToError(RequestMappingIntercessor.java:63) ~[TeamLand.jar:?]
>         at com.qiwi.billpayments.sdk.client.RequestMappingIntercessor.deserializeResponseBody(RequestMappingIntercessor.java:54) ~[TeamLand.jar:?]
>         at com.qiwi.billpayments.sdk.client.RequestMappingIntercessor.request(RequestMappingIntercessor.java:34) ~[TeamLand.jar:?]
>         at com.qiwi.billpayments.sdk.client.BillPaymentClient.createBill(BillPaymentClient.java:47) ~[TeamLand.jar:?]
>         at com.kaiyofx.teamland.telegram.TelegramManager.createBill(TelegramManager.java:214) ~[TeamLand.jar:?]
>         at com.kaiyofx.teamland.telegram.TelegramManager.onUpdateReceived(TelegramManager.java:180) ~[TeamLand.jar:?]
>         at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
>         at org.telegram.telegrambots.meta.generics.LongPollingBot.onUpdatesReceived(LongPollingBot.java:27) ~[TeamLand.jar:?]
>         at org.telegram.telegrambots.updatesreceivers.DefaultBotSession$HandlerThread.run(DefaultBotSession.java:317) ~[TeamLand.jar:?]

**Comment by PukPukov** [comment]
Эта SDK заброшена, судя по всему. Я взял один из пулл реквестов, где фиксится этот баг и на основе его сделал новый репозиторий. 
https://github.com/PukPukov/bill-payments-java-sdk/

**Comment by kaiyofx** [comment]
Вау. Спасибо большое.
А не подскажите как добавлять свои customFields. К примеру customFields.themeCode

**Comment by PukPukov** [comment]
> Вау. Спасибо большое. А не подскажите как добавлять свои customFields. К примеру customFields.themeCode

Судя по всему надо и дальше дорабатывать SDK, в ней такого функционала нет. Сейчас у меня нет времени этим заниматься, можешь сделать сам и кинуть пулл реквест

**Comment by kaiyofx** [comment]
А через что это можно реализовать?

**Comment by PukPukov** [comment]
Сдк отправлять жсоны по хттп, надо просто добавить поле в отправляемом жсоне

**Comment by kaiyofx** [comment]
Спасибо.
